### ISSUE TITLE
Integrate ZenDesk API lib into app

### ISSUE THREAD

**Issue by sfaria27** [tiki/zendesk_flutter#13]
Replace support modal by ZenDesk flutter lib 

Acceptance criteria:
1. Support modal should appear after replacement

**Comment by ricardobrg** [comment]
moving to sprint 9 in favor of money sdk

**Comment by ricardobrg** [comment]
https://user-images.githubusercontent.com/8357343/156236882-34e50ec0-7332-4c76-9927-ab61cd1f4922.mp4
