### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ricardobrg** [tiki/zendesk_flutter#5]
Create integration tests for zendesk api and ui.

**Comment by ricardobrg** [comment]
Test scenario 1:
The user is able to open the support modal from example app button.

Test case 1:
- Start the example app
- Find the button to open the modal and tap
- Wait 2s to load the content
- Check if the text "welcome to our help center..." is shown above the cards 

![Simulator Screen Shot - iPhone 13 - 2022-03-28 at 15 49 22](https://user-images.githubusercontent.com/8357343/160466872-ad08039c-890a-440e-a496-561724ff6155.png)

https://github.com/tiki/app/issues/440

**Comment by NickkTMD** [comment]
Waiting on fixing example app on android to do this
